#静态文件访问配置
spring:
  mvc:
    static-path-pattern: /**
  datasource:
    driver-class-name: com.mysql.jdbc.Driver          # mysql驱动
    url: jdbc:mysql://localhost:3306/db1?useUnicode=true&characterEncoding=utf-8&useOldAliasMetadataBehavior=true&serverTimezone=UTC
    username: root
    password: root
#更改服务端口
server:
  port: 9090


logging:
  file:
    name: ./logs/demo.log


